use_frameworks!

platform :ios, '11.0'

target 'AppDeviceSystemInfo_Example' do
  pod 'AppDeviceSystemInfo', :path => '../AppDeviceSystemInfo.podspec'

  target 'AppDeviceSystemInfo_Tests' do
    inherit! :search_paths
    
  end
end
