use_frameworks!

platform :ios, '9.0'

target 'AppDeviceSystemInfo_Example' do
  pod 'AppDeviceSystemInfo', :path => '../'

  target 'AppDeviceSystemInfo_Tests' do
    inherit! :search_paths

    
  end
end
